# Modifification of the default openshift DNS Operator to
# include DNS forwarding zones for the services in the meemoo
# datacenters.
# cfr. https://docs.openshift.com/dedicated/4/networking/dns-operator.html
# Usage: oc edit dns.operator/default
apiVersion: operator.openshift.io/v1
kind: DNS
metadata:
  name: default
spec:
  servers:
  - name: do.viaa.be
    forwardPlugin:
      upstreams:
      - 10.50.104.2
      - 10.50.136.2
      - 10.50.40.2
    zones:
    - do.viaa.be
    - dg.viaa.be
