apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress-controller-int
  namespace: nginx-ingress
  annotations:
    service.kubernetes.io/ibm-load-balancer-cloud-provider-enable-features: "proxy-protocol"
    service.kubernetes.io/ibm-load-balancer-cloud-provider-ip-type: "private"
    service.kubernetes.io/ibm-load-balancer-cloud-provider-zone: "eu-de-1"
spec:
  type: LoadBalancer
  selector:
    app: nginx-ingress-controller-qas
  ports:
   - name: http
     protocol: TCP
     port: 80
     targetPort: http
   - name: https
     protocol: TCP
     port: 443
     targetPort: https
  externalTrafficPolicy: Local
  sessionAffinity: None
