apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: nginx-ingess-controller.tpl
  namespace: nginx-ingress
  annotations:
    meemoo.be/source: "https://github.com/viaacode/ibmcloud.git"
    description: >-
      Creates meemoo-specific configuration for the nginx ingress controller
      Used iso the operator as the operateor does not provide the annototaions needed for the service
objects:
  - apiVersion: networking.k8s.io/v1
    kind: IngressClass
    metadata:
      annotations:
        meemoo.be/source: "https://github.com/viaacode/ibmcloud.git"
      name: nginx-${Env}
    spec:
      controller: nginx.org/ingress-controller
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      annotations:
        meemoo.be/source: "https://github.com/viaacode/ibmcloud.git"
      name: nginx-config-${Env}
      namespace: nginx-ingress
    data:
      proxy-protocol: "True"
      real-ip-header: "proxy_protocol"
      set-real-ip-from: ${LB_SUBNET}
      real-ip-recursive: 'True'
      http-snippets: ${{HttpSnippet}}
  - apiVersion: v1
    kind: Service
    metadata:
      name: nginx-ingress-controller-${Env}
      namespace: nginx-ingress
      annotations:
        meemoo.be/source: "https://github.com/viaacode/ibmcloud.git"
        service.kubernetes.io/ibm-load-balancer-cloud-provider-enable-features: "proxy-protocol"
        service.kubernetes.io/ibm-load-balancer-cloud-provider-ip-type: "${SCOPE}"
        service.kubernetes.io/ibm-load-balancer-cloud-provider-zone: "eu-de-1"
    spec:
      type: LoadBalancer
      selector:
        app: nginx-ingress-controller-${Env}
      ports:
       - name: http
         protocol: TCP
         port: 80
         targetPort: http
       - name: https
         protocol: TCP
         port: 443
         targetPort: https
      externalTrafficPolicy: Local
      sessionAffinity: None
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      annotations:
        meemoo.be/source: "https://github.com/viaacode/ibmcloud.git"
        image.openshift.io/triggers: >-
          [{"from": {"kind": "ImageStreamTag", "name": "nginx-plus-ingress:${Env}"}, "fieldPath":
            "spec.template.spec.containers[?(@.name==\"nginx-ingress-controller-${Env}\")].image"}]
      name: nginx-ingress-controller-${Env}
      namespace: nginx-ingress
    spec:
      replicas: ${{NPODS}}
      selector:
        matchLabels:
          app: nginx-ingress-controller-${Env}
      strategy:
        rollingUpdate:
          maxSurge: 25%
          maxUnavailable: 25%
        type: RollingUpdate
      template:
        metadata:
          labels:
            app: nginx-ingress-controller-${Env}
          name: nginx-ingress-controller-${Env}
        spec:
          containers:
          - args:
            - -nginx-configmaps=nginx-ingress/nginx-config-${Env}
            - -default-server-tls-secret=nginx-ingress/${DefaultTlsSecretName}
            - -nginx-plus
            - -leader-election-lock-name=nginx-ingress-controller-lock-${Env}
            - -wildcard-tls-secret=nginx-ingress/${DefaultTlsSecretName}
            - -ingress-class=nginx-${Env}
            - -enable-snippets=${SNIPPETS}
            env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            image: image-registry.openshift-image-registry.svc:5000/nginx-ingress/nginx-plus-ingress:${Env}
            imagePullPolicy: IfNotPresent
            name: nginx-ingress-controller-${Env}
            ports:
            - containerPort: 80
              name: http
              protocol: TCP
            - containerPort: 443
              name: https
              protocol: TCP
            - containerPort: 8081
              name: readiness-port
              protocol: TCP
            - containerPort: 9113
              name: prometheus
              protocol: TCP
            readinessProbe:
              httpGet:
                path: /nginx-ready
                port: readiness-port
              periodSeconds: 1
            securityContext:
              allowPrivilegeEscalation: true
              capabilities:
                add:
                - NET_BIND_SERVICE
                drop:
                - ALL
              runAsUser: 101
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          serviceAccount: nginx-ingress
          serviceAccountName: nginx-ingress
          terminationGracePeriodSeconds: 30
parameters:
  - description: Environment (prd, qas, int or dev)
    displayName: Environment
    name: Env 
    required: true
  - description: exposure scope (private or public)
    displayName: scope
    name: SCOPE
    required: true
  - description: Subnet of the loadbalancers (allow proxy protocol)
    displayName: lb-subnet
    name: LB_SUBNET
    required: true
  - description: Number of replica's for the ingress controller pods
    displayName: n-pods
    name: NPODS
    value: "1"
  - description: Default Tls Secret
    displayName: default-tls-secret-name
    name: DefaultTlsSecretName
    required: true
  - description: raw NGINX configuration snippet inserted in http context
    displayName: http-snippet
    name: HttpSnippet
    required: false
  - description: Enable Snippets
    displayName: snippets
    name: SNIPPETS
    value: "true"
